version: 2

sources:
  - name: projetofinal
    description: Esta é uma réplica do banco de dados Postgres usado pela Adventure Works.
    tables:
      - name: production_product
        description: >
          Dados referentes aos produtos.
        columns:
          - name: productid
            description: é a chave primária da tabela
            tests:
              - unique
              - not_null
           
      - name: public_address
      - name: public_customer
      - name: sales_creditcar
      - name: sales_salesorderdetail
      - name: sales_salesorderheader
      - name: sales_salesorderheadersalesreason
      - name: sales_salesreason


